version: '3'
services:
  appseed-app:
    restart: always
    env_file: ./webapp/env
    build:
      context: ./webapp
      network: host
    ports:
      - "5005:5005"
  backend-app:
    restart: always
    env_file: ./backend/env
    build:
      context: ./backend
      network: host
    volumes:
      - ./notebooks:/app/backend/notebooks
      - ./notebooks:/app/backend/notebook
      - ./src:/app/backend/src
      - ./data-processed:/app/backend/data-processed
      - ./data-raw:/app/backend/data-raw

