version: '3'
services:
  appseed-app:
    restart: always
    env_file: ./env
    build: .
    ports:
      - "5005:5005"
    networks:
      - db_network
      - web_network
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge